
name: Log on Main Push

on:
  push:
    branches:
      - main

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log Push Event
        run: echo "Push event detected on the main branch." 
